name: kai-usdc

on:
  push:
    paths:
      - "kai-usdc.js"
  schedule:
    - cron: "* * * * *"

jobs:
  kai-usdc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}

      - run: npm i
      - run: node kai-usdc.js
      - run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add kai-usdc.json -f
          git commit -m "Update kai-usdc.json"
          git fetch --all
          git checkout gh-pages
          git checkout main kai-usdc.json
          git add kai-usdc.json -f
          git commit --amend -m "Update data"
          git push --force
